"""Run the cross-host git bridge as a systemd **user** service.

Until now the only thing that started ``bin/dispatch-gitsync`` was
``hooks/dispatch-gitsync-arm.py``, a *Claude Code* SessionStart/Stop hook. Agents
on any other harness (openclaw, Hermes, a plain script, the TUI, a human) never
fired it, so no daemon ran, nothing pushed, nothing fetched — and the only way to
exchange a message was to ``git pull``/``git push`` by hand. This module makes the
daemon harness-independent: one user-level unit, started at login, restarted on
failure, entirely unaware of which agent runtime is talking through the relay.

The rendered unit is deliberately conservative about sandboxing. Over-hardening a
process that has to run ``git`` (which in turn runs ``ssh``, reads credentials,
and talks to the network) breaks it in ways that look like the very "talking to a
wall" symptom this is here to fix, so each directive below is one we can justify:

* ``ProtectSystem=full`` (not ``strict``) — /usr, /boot, /efi and /etc read-only,
  while $HOME and /run stay writable. ``strict`` would also freeze ``/run/user``,
  cutting the ssh-agent socket, and ``~/.ssh/known_hosts``.
* ``PrivateTmp`` **only** when neither the relay nor the clone lives under /tmp or
  /var/tmp — the private namespace would otherwise hide the very directory the
  daemon exists to mirror. ``dispatch_dir = "/var/tmp/mcp-dispatch"`` is the
  documented group-mode layout, so this is a real case, not a hypothetical.
* ``UMask`` follows ``group_mode`` exactly as ``server.py`` does, so materialized
  messages land 0660 in a shared relay and 0600 otherwise — a sandbox that quietly
  widened permissions would be worse than none.

Everything interpolated into the unit is validated and escaped (`systemd_user.esc`):
a unit file is a config format with its own metacharacter (``%``) and its own
quoting rules, and the values here come from a user config file, so they get
treated as untrusted input rather than pasted in raw. That escaping, and the
write/enable/restart dance around it, live in ``systemd_user`` because the
lifecycle supervisor installs a unit too and must not carry a second copy.
"""

from __future__ import annotations

from pathlib import Path

import systemd_user
from systemd_user import ServiceError, validate_env  # noqa: F401 - re-exported API

UNIT_NAME = "mcp-dispatch-gitsync.service"

_NO_SYSTEMD_HINT = "bin/dispatch-gitsync --no-presence-gate"


def render_unit(
    *,
    python: str,
    daemon: Path,
    repo_root: Path,
    config_path: Path,
    dispatch_dir: Path,
    repo_dir: Path,
    state_dir: Path,
    group_mode: bool = False,
    interval: float | None = None,
    env: dict[str, str] | None = None,
) -> str:
    """Render the systemd user unit as text. Pure — writes nothing, so it is the
    seam the tests drive."""
    exec_args = [python, str(daemon), "--no-presence-gate"]
    if interval is not None:
        exec_args += ["--interval", repr(float(interval))]
    exec_start = " ".join(systemd_user.quote_arg(a) for a in exec_args)

    # MCP_DISPATCH_CONFIG is baked in unconditionally: a user service inherits
    # almost nothing from the login shell, so relying on the ambient value would
    # make the service resolve a *different* config than the CLI did at install.
    # PYTHONUNBUFFERED so `journalctl -f` shows progress live rather than in 8KB
    # bursts — a bridge you can't watch is one you can't diagnose.
    env_lines = systemd_user.env_lines(
        {
            "MCP_DISPATCH_CONFIG": str(config_path),
            "PYTHONUNBUFFERED": "1",
            **(env or {}),
        }
    )

    # Only the three trees the daemon actually writes. Listed even under
    # ProtectSystem=full (which leaves $HOME writable) so tightening to `strict`
    # later is a one-word change rather than a rediscovery of these paths.
    rw = systemd_user.read_write_paths([dispatch_dir, repo_dir, state_dir])
    namespaced = systemd_user.under_tmp(dispatch_dir) or systemd_user.under_tmp(repo_dir)
    private_tmp = "no" if namespaced else "yes"
    umask = "0007" if group_mode else "0077"

    return f"""\
# Generated by `dispatch-gitsync service install`. Re-run that to regenerate;
# local edits are overwritten. See gitsync_service.py for why each knob is set.
[Unit]
Description=mcp-dispatch cross-host git bridge
Documentation=https://github.com/justinstimatze/mcp-dispatch
After=network-online.target
Wants=network-online.target
# A crash loop must not hammer the git remote: give up after 10 restarts in 5min.
StartLimitIntervalSec=300
StartLimitBurst=10

[Service]
Type=simple
WorkingDirectory={systemd_user.esc(str(repo_root))}
ExecStart={exec_start}
{env_lines}
Restart=always
RestartSec=5
# Materialized messages inherit the relay's sharing model, exactly as server.py.
UMask={umask}

# -- sandboxing (see module docstring: git/ssh need net, $HOME and /run) -------
# Everything here is seccomp- or namespace-based. Deliberately NO ProtectClock,
# ProtectControlGroups, ProtectKernelTunables or ProtectKernelModules: each implies
# a CapabilityBoundingSet change, which a *user* manager cannot perform — the unit
# then dies at spawn with 218/CAPABILITIES before running a line of Python. They
# also guard operations an unprivileged process could never do in the first place.
NoNewPrivileges=yes
ProtectSystem=full
RestrictSUIDSGID=yes
RestrictRealtime=yes
RestrictNamespaces=yes
LockPersonality=yes
# AF_UNIX for the ssh-agent socket, AF_INET/6 for the git remote. Nothing else.
RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6
SystemCallFilter=@system-service
SystemCallErrorNumber=EPERM
PrivateTmp={private_tmp}
{rw}

[Install]
WantedBy=default.target
"""


# ---------------------------------------------------------------------------
# Install / uninstall — thin bindings of this unit's name to the shared driver
# ---------------------------------------------------------------------------


def unit_path() -> Path:
    return systemd_user.unit_path(UNIT_NAME)


def systemctl_available() -> bool:
    return systemd_user.systemctl_available()


def install(unit_text: str, *, enable: bool = True, dry_run: bool = False) -> list[str]:
    return systemd_user.install(
        UNIT_NAME, unit_text, enable=enable, dry_run=dry_run, no_systemd_hint=_NO_SYSTEMD_HINT
    )


def uninstall(*, dry_run: bool = False) -> list[str]:
    return systemd_user.uninstall(UNIT_NAME, dry_run=dry_run)


def status_lines() -> list[str]:
    """Short human-readable service status for `dispatch-gitsync status`."""
    return systemd_user.status_lines(UNIT_NAME, "dispatch-gitsync service install")
