"""Run the lifecycle supervisor as a systemd **user** service.

The supervisor is the one dispatch daemon that is useless unless it outlives
every session: it exists to start an agent when *nothing* is running, so a
supervisor that only runs while an agent is running would never fire. It is
therefore always ungated, always a service.

Why this unit is barely sandboxed, unlike the gitsync one
---------------------------------------------------------
A unit's sandbox is inherited by everything the service spawns, and what this
service spawns is, by design, an arbitrary program the operator named — an agent
runtime that will want the network, the user's credentials, a terminal-ish
environment and whatever else its harness assumes. gitsync can afford
``SystemCallFilter`` and ``RestrictAddressFamilies`` because it runs exactly one
known thing (``git``). Applying that profile here would break the child in ways
that surface as "the agent starts and immediately dies", which is precisely the
symptom the supervisor is supposed to *cure*, and the cause would be two layers
away from the error message.

So: ``NoNewPrivileges`` (the child should not gain privileges it wasn't started
with) and ``ProtectSystem=full`` (the system tree is read-only; $HOME is not) —
both of which an agent runtime can live with — and nothing that filters syscalls
or address families. The real containment for this feature is the allowlist in
``supervisor.py``, not the unit file.
"""

from __future__ import annotations

from pathlib import Path

import systemd_user
from systemd_user import ServiceError, validate_env  # noqa: F401 - re-exported API

UNIT_NAME = "mcp-dispatch-supervise.service"

_NO_SYSTEMD_HINT = "bin/dispatch-supervise"


def render_unit(
    *,
    python: str,
    daemon: Path,
    repo_root: Path,
    config_path: Path,
    dispatch_dir: Path,
    state_dir: Path,
    log_dir: Path,
    interval: float | None = None,
    env: dict[str, str] | None = None,
) -> str:
    """Render the systemd user unit as text. Pure — writes nothing."""
    exec_args = [python, str(daemon)]
    if interval is not None:
        exec_args += ["--interval", repr(float(interval))]
    exec_start = " ".join(systemd_user.quote_arg(a) for a in exec_args)

    # MCP_DISPATCH_CONFIG is baked in: a user service inherits almost nothing from
    # the login shell, and this config is the allowlist — resolving a *different*
    # one than the CLI validated would be the worst possible surprise here.
    env_lines = systemd_user.env_lines(
        {
            "MCP_DISPATCH_CONFIG": str(config_path),
            "PYTHONUNBUFFERED": "1",
            **(env or {}),
        }
    )
    rw = systemd_user.read_write_paths([dispatch_dir, state_dir, log_dir])
    private_tmp = "no" if systemd_user.under_tmp(dispatch_dir) else "yes"

    return f"""\
# Generated by `dispatch-supervise service install`. Re-run that to regenerate;
# local edits are overwritten. See supervisor_service.py for why the sandbox is
# deliberately light: everything this unit starts inherits it.
[Unit]
Description=mcp-dispatch lifecycle supervisor (start an agent when mail is waiting)
Documentation=https://github.com/justinstimatze/mcp-dispatch
After=network-online.target
Wants=network-online.target
StartLimitIntervalSec=300
StartLimitBurst=10

[Service]
Type=simple
WorkingDirectory={systemd_user.esc(str(repo_root))}
ExecStart={exec_start}
{env_lines}
Restart=always
RestartSec=5
# KillMode=process: on stop/restart, kill the supervisor and NOT the agents it
# started. Restarting the babysitter must not kill the children — an upgrade
# would otherwise take down every running agent on the host.
KillMode=process

# -- sandboxing: deliberately minimal, see the module docstring ---------------
NoNewPrivileges=yes
ProtectSystem=full
{rw}
PrivateTmp={private_tmp}

[Install]
WantedBy=default.target
"""


def unit_path() -> Path:
    return systemd_user.unit_path(UNIT_NAME)


def systemctl_available() -> bool:
    return systemd_user.systemctl_available()


def install(unit_text: str, *, enable: bool = True, dry_run: bool = False) -> list[str]:
    return systemd_user.install(
        UNIT_NAME, unit_text, enable=enable, dry_run=dry_run, no_systemd_hint=_NO_SYSTEMD_HINT
    )


def uninstall(*, dry_run: bool = False) -> list[str]:
    return systemd_user.uninstall(UNIT_NAME, dry_run=dry_run)


def status_lines() -> list[str]:
    return systemd_user.status_lines(UNIT_NAME, "dispatch-supervise service install")
