"""Run the native-protocol bridge (dispatch-ucbridge) as a systemd user service.

Until now the only way to run this daemon at all was by hand or under
whatever supervisor the operator happened to have — there was no
harness-independent way to keep it running, unlike ``dispatch-gitsync``. This
module is the same fix applied here: one user-level unit, started at login,
restarted on failure, unaware of which agent runtime (if any) is talking
through the relay.

One subtlety this unit gets wrong if copied carelessly from
``gitsync_service.py``: **``PrivateTmp`` must always be ``no``.** The default
socket directory (``/tmp/cc-socks/``, see ``bridge_native.DEFAULT_SOCKET_DIR``)
is not scratch space this daemon owns privately — it's the shared location
EVERY Claude Code session on the host, running unsandboxed in the real
``/tmp``, expects to find these sockets in. A private ``/tmp`` namespace would
still let the daemon bind and accept connections happily; it would just be
binding inside a mount only this unit can see, so no other session could ever
reach it — the exact "talking to a wall" symptom ``gitsync_service.py``
documents for a different cause. So this is not computed per-install the way
gitsync's ``PrivateTmp`` is (whether the RELAY happens to live under /tmp);
it's a hard-coded ``no``, because the SOCKET directory living under /tmp is
the common case, not an edge case.

The other simplification relative to ``gitsync_service.py``: this daemon never
touches the network or spawns ``git``/``ssh``, so ``RestrictAddressFamilies``
drops to ``AF_UNIX`` only and ``ProtectSystem`` can go to ``strict`` (everything
read-only except the four trees this daemon actually writes) instead of
``full`` — gitsync needs ``full`` for ssh-agent/known_hosts access under
unpredictable paths; this daemon's writes are exactly ``dispatch_dir``,
``socket_dir``, ``sessions_dir`` and ``state_dir``, all named explicitly below.

Escaping (``systemd_user.esc``) and the write/enable/restart dance are shared
with every other dispatch daemon's service module — see gitsync_service.py's
docstring for why that lives in ``systemd_user`` rather than here.
"""

from __future__ import annotations

from pathlib import Path

import systemd_user
from systemd_user import ServiceError, validate_env  # noqa: F401 - re-exported API

UNIT_NAME = "mcp-dispatch-ucbridge.service"

_NO_SYSTEMD_HINT = "bin/dispatch-ucbridge --no-presence-gate"


def render_unit(
    *,
    python: str,
    daemon: Path,
    repo_root: Path,
    config_path: Path,
    dispatch_dir: Path,
    socket_dir: Path,
    sessions_dir: Path,
    state_dir: Path,
    group_mode: bool = False,
    interval: float | None = None,
    env: dict[str, str] | None = None,
) -> str:
    """Render the systemd user unit as text. Pure — writes nothing, so it is the
    seam the tests drive."""
    exec_args = [python, str(daemon), "--no-presence-gate"]
    if interval is not None:
        exec_args += ["--interval", repr(float(interval))]
    exec_start = " ".join(systemd_user.quote_arg(a) for a in exec_args)

    # MCP_DISPATCH_CONFIG is baked in unconditionally: a user service inherits
    # almost nothing from the login shell, so relying on the ambient value would
    # make the service resolve a *different* config than the CLI did at install.
    env_lines = systemd_user.env_lines(
        {
            "MCP_DISPATCH_CONFIG": str(config_path),
            "PYTHONUNBUFFERED": "1",
            **(env or {}),
        }
    )

    rw = systemd_user.read_write_paths([dispatch_dir, socket_dir, sessions_dir, state_dir])
    umask = "0007" if group_mode else "0077"

    return f"""\
# Generated by `dispatch-ucbridge service install`. Re-run that to regenerate;
# local edits are overwritten. See ucbridge_service.py for why each knob is set.
[Unit]
Description=mcp-dispatch native-protocol bridge
Documentation=https://github.com/justinstimatze/mcp-dispatch
# A crash loop must not spin forever: give up after 10 restarts in 5min.
StartLimitIntervalSec=300
StartLimitBurst=10

[Service]
Type=simple
WorkingDirectory={systemd_user.esc(str(repo_root))}
ExecStart={exec_start}
{env_lines}
Restart=always
RestartSec=5
# Materialized messages inherit the relay's sharing model, exactly as server.py.
UMask={umask}

# -- sandboxing (see module docstring for PrivateTmp and the AF_UNIX-only note) -
NoNewPrivileges=yes
ProtectSystem=strict
RestrictSUIDSGID=yes
RestrictRealtime=yes
RestrictNamespaces=yes
LockPersonality=yes
# This daemon never touches the network — local Unix sockets only.
RestrictAddressFamilies=AF_UNIX
SystemCallFilter=@system-service
SystemCallErrorNumber=EPERM
# MUST be "no" — see the module docstring. /tmp/cc-socks is shared, not private.
PrivateTmp=no
{rw}

[Install]
WantedBy=default.target
"""


# ---------------------------------------------------------------------------
# Install / uninstall — thin bindings of this unit's name to the shared driver
# ---------------------------------------------------------------------------


def unit_path() -> Path:
    return systemd_user.unit_path(UNIT_NAME)


def systemctl_available() -> bool:
    return systemd_user.systemctl_available()


def install(unit_text: str, *, enable: bool = True, dry_run: bool = False) -> list[str]:
    return systemd_user.install(
        UNIT_NAME, unit_text, enable=enable, dry_run=dry_run, no_systemd_hint=_NO_SYSTEMD_HINT
    )


def uninstall(*, dry_run: bool = False) -> list[str]:
    return systemd_user.uninstall(UNIT_NAME, dry_run=dry_run)


def status_lines() -> list[str]:
    """Short human-readable service status for `dispatch-ucbridge status`."""
    return systemd_user.status_lines(UNIT_NAME, "dispatch-ucbridge service install")
