// service.go — `dispatch-ircd service install`: a systemd user unit.
//
// The gateway is only useful if it is running when you open your client, and
// "remember to start it in a spare terminal" is not a plan. This mirrors what
// `dispatch-gitsync service install` already does for the git bridge, including
// the traps that make hand-written units fail silently:
//
//   - '%' is a systemd *specifier* ('%h' is your home dir), so an unescaped '%'
//     in a path quietly rewrites it. Every interpolated value is escaped.
//   - A control character ends the directive and starts a forged one. Refused.
//   - A *user* manager cannot change the capability bounding set, so any
//     directive implying one (ProtectClock, ProtectKernelTunables, …) kills the
//     unit at spawn with 218/CAPABILITIES before a line of it runs. None are
//     emitted, deliberately.
//
// The unit bakes absolute paths, so re-run install after moving the repo or
// rebuilding the binary — it is idempotent, and doubles as the upgrade path.
package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

const unitName = "dispatch-ircd.service"

// esc makes a value safe to interpolate into a unit directive.
func esc(v string) (string, error) {
	for _, r := range v {
		if r < 0x20 || r == 0x7F {
			return "", fmt.Errorf("control character in unit value: %q", v)
		}
	}
	return strings.ReplaceAll(v, "%", "%%"), nil
}

// quoteArg quotes one ExecStart argument — systemd applies shell-ish splitting,
// so a path with a space would otherwise become two arguments.
func quoteArg(v string) (string, error) {
	e, err := esc(v)
	if err != nil {
		return "", err
	}
	e = strings.ReplaceAll(e, `\`, `\\`)
	e = strings.ReplaceAll(e, `"`, `\"`)
	return `"` + e + `"`, nil
}

func unitDir() string {
	if x := os.Getenv("XDG_CONFIG_HOME"); x != "" {
		return filepath.Join(x, "systemd", "user")
	}
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".config", "systemd", "user")
}

func unitPath() string { return filepath.Join(unitDir(), unitName) }

// renderUnit builds the unit text for this binary and config.
func renderUnit(c Config, relayDir, exePath, configPath string) (string, error) {
	exeQ, err := quoteArg(exePath)
	if err != nil {
		return "", err
	}
	relayQ, err := esc(relayDir)
	if err != nil {
		return "", err
	}

	// Only pin MCP_DISPATCH_CONFIG when it was explicitly set — otherwise the
	// service should resolve config the same way an interactive run does.
	envLines := ""
	if configPath != "" {
		cq, err := esc(configPath)
		if err != nil {
			return "", err
		}
		envLines = fmt.Sprintf("Environment=MCP_DISPATCH_CONFIG=%s\n", cq)
	}

	// A TCP listener needs the network up first; a pure unix-socket gateway
	// does not, and ordering on it would just delay start for no reason.
	netAfter := ""
	if c.Listen != "" {
		netAfter = "After=network-online.target\nWants=network-online.target\n"
	}

	// PrivateTmp namespaces /tmp and /var/tmp away. The documented group-mode
	// relay layout lives under /var/tmp, so it is dropped in that case rather
	// than silently serving an empty relay.
	privateTmp := "yes"
	if strings.HasPrefix(filepath.Clean(relayDir), "/var/tmp") ||
		strings.HasPrefix(filepath.Clean(relayDir), "/tmp") {
		privateTmp = "no"
	}

	umask := "0077"
	if strings.Contains(relayDir, "/var/tmp") {
		umask = "0007" // group-mode relays are group-shared, matching server.py
	}

	return fmt.Sprintf(`# Generated by `+"`dispatch-ircd service install`"+`. Re-run that to regenerate;
# local edits are overwritten. See tui/ircd/service.go for why each knob is set.
[Unit]
Description=mcp-dispatch IRC gateway
Documentation=https://github.com/justinstimatze/mcp-dispatch/blob/main/docs/irc-gateway.md
%s# A crash loop must not spin: give up after 10 restarts in 5 minutes.
StartLimitIntervalSec=300
StartLimitBurst=10

[Service]
Type=simple
ExecStart=%s
%sRestart=always
RestartSec=5
# Message files the gateway writes inherit the relay's sharing model.
UMask=%s

# -- sandboxing ---------------------------------------------------------------
# Deliberately NO ProtectClock/ProtectKernelTunables/ProtectKernelModules/
# ProtectControlGroups: each implies a CapabilityBoundingSet change a *user*
# manager cannot perform, and the unit then dies at spawn with 218/CAPABILITIES.
NoNewPrivileges=yes
ProtectSystem=full
RestrictSUIDSGID=yes
RestrictRealtime=yes
RestrictNamespaces=yes
LockPersonality=yes
# AF_UNIX for the gateway socket, AF_INET/6 only if a TCP listener is configured.
RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6
SystemCallFilter=@system-service
SystemCallErrorNumber=EPERM
PrivateTmp=%s
ReadWritePaths=%s

[Install]
WantedBy=default.target
`, netAfter, exeQ, envLines, umask, privateTmp, relayQ), nil
}

func systemctlAvailable() bool {
	_, err := exec.LookPath("systemctl")
	return err == nil
}

func systemctl(args ...string) error {
	cmd := exec.Command("systemctl", append([]string{"--user"}, args...)...) //nolint:gosec // fixed binary, fixed args
	cmd.Stdout, cmd.Stderr = os.Stdout, os.Stderr
	return cmd.Run()
}

func systemctlOut(args ...string) string {
	cmd := exec.Command("systemctl", append([]string{"--user"}, args...)...) //nolint:gosec // fixed binary, fixed args
	out, _ := cmd.Output()
	return strings.TrimSpace(string(out))
}

// serviceInstall writes the unit and enables it. Idempotent: re-running
// regenerates from current config and restarts onto it, which is also how you
// pick up a rebuilt binary — systemd keeps running the process it started, so a
// `git pull` alone leaves the old code live.
func serviceInstall(unitText string, dryRun bool) error {
	if !systemctlAvailable() {
		return fmt.Errorf("systemctl not found — run the gateway under whatever supervisor you do have:\n" +
			"  dispatch-ircd     (it is a plain foreground process that exits on SIGTERM)")
	}
	path := unitPath()
	if dryRun {
		fmt.Printf("would write %s (0600)\n", path)
		fmt.Println("would run  systemctl --user daemon-reload")
		fmt.Printf("would run  systemctl --user enable --now %s\n", unitName)
		return nil
	}
	if err := os.MkdirAll(unitDir(), 0o700); err != nil {
		return err
	}
	// 0600 before any content lands: the unit can name a config path, and a
	// future --env would carry more than that.
	if err := os.WriteFile(path, []byte(unitText), 0o600); err != nil {
		return err
	}
	fmt.Printf("wrote %s\n", path)
	if err := systemctl("daemon-reload"); err != nil {
		return err
	}
	_ = systemctl("reset-failed", unitName) // clear a latched failure from a previous unit
	if err := systemctl("enable", unitName); err != nil {
		return err
	}
	if err := systemctl("restart", unitName); err != nil {
		return err
	}
	fmt.Printf("enabled and started %s\n", unitName)
	fmt.Printf("  journalctl --user -u %s -f\n", unitName)
	return nil
}

func serviceUninstall(dryRun bool) error {
	path := unitPath()
	if dryRun {
		fmt.Printf("would run    systemctl --user disable --now %s\n", unitName)
		fmt.Printf("would remove %s\n", path)
		return nil
	}
	if systemctlAvailable() {
		_ = systemctl("disable", "--now", unitName)
	}
	if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
		return err
	}
	fmt.Printf("removed %s\n", path)
	return nil
}

func serviceStatus() {
	path := unitPath()
	if _, err := os.Stat(path); err != nil {
		fmt.Printf("unit         not installed (%s)\n", path)
	} else {
		fmt.Printf("unit         %s\n", path)
	}
	if !systemctlAvailable() {
		fmt.Println("systemctl    not available")
		return
	}
	fmt.Printf("active       %s\n", orUnknown(systemctlOut("is-active", unitName)))
	fmt.Printf("enabled      %s\n", orUnknown(systemctlOut("is-enabled", unitName)))
}

func orUnknown(s string) string {
	if s == "" {
		return "unknown"
	}
	return s
}

// lingerHint is printed after a successful install. A user manager does not
// start at boot unless lingering is on, and on many distros it is torn down
// with your last login session — so on a headless box the gateway would run
// only while you happen to be logged in, which looks exactly like it being
// broken.
const lingerHint = `
If this host has no graphical login (a server, or you connect over ssh), enable
lingering once, or the user manager — and this unit with it — won't survive
your logout:

    sudo loginctl enable-linger $USER
`
